name: Cron
on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  cron:
    name: Cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run application
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE: ${{ secrets.FIGMA_FILE }}
        run: npm run start
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Cron: Automated update"
